### PR TITLE
Removed unused dependencies. Added 'Bearer ' prefix to Authentication token. Fixed default voice value.

### PR DESCRIPTION
**Pull request by Domratchev**
Also added ability to install from GitHub repo, which may not be desirable(?)

### CODE REVIEW

**Comment by compulim** [comment]
IMO, publishing transpiled bits introduce many issues like inconsistencies and "it works on my machine" problems. This is because the build environment can be polluted for many reasons. Thus, we prefer bits to be transpiled on Travis CI to make sure it is clean and can be served as a baseline.

"When my PR will land?" We have `master` tag on NPM, which is in-sync with `master` branch on GitHub. As soon as the PR is merged, Travis will release a new build to NPM with `master` tag.

Peer dependencies is also very important for packages. Without peer dependencies, the user of this package are forced to install specific version of React, which will severly limit the user of this package.

Will take part of the PR.

**Comment by Domratchev** [comment]
Hi William,

I did not see the Travis stuff in my repo - hence the inclusion of the transpiled files.
Yet the very intent of the changes was the removal of React dependencies from the library itself it is as useful in Angular projects (my case) as in React ones, and I am sure could be used with other frameworks as well.

Thank you for your work!

Alexei

**Comment by Domratchev** [comment]
Hi William,

I've made a few changes to you library to support unified SpeechService API and server-side authorization token retrieval.

Please have a look at the recent commits, when you have time.

Best regards,

Alexei

**Comment by compulim** [comment]
Sorry was busy working on the new Speech Services SDK integration.

Will look at your PR to see what changes I can integrate into the newer release.

**Pull request closed without merging**
